Bu yerda

In [12]:
import numpy as np
import pandas as pd

In [2]:
!wget https://github.com/anvarnarz/praktikum_datasets

"wget" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

In [13]:
df = pd.read_csv("praktikum_datasets/uzbekistan.csv")
df.head()

          Boʻlinishi  Maydoni (kv.km)    Aholisi
0   Andijon viloyati           4200.0  1899000.0
1    Buxoro viloyati          39400.0  1384700.0
2  Fargʻona viloyati           6800.0  2597000.0
3    Jizzax viloyati          20500.0   910500.0
4    Xorazm viloyati           6300.0  1200000.0

In [ ]:
pd.read_excel('praktikum_datasets/uzbekistan.xlsx', index_col=0, names=['hudud', 'maydon', 'aholi'])

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000