Bu yerda

In [1]:
import numpy as np
import pandas as pd

In [2]:
!git clone https://github.com/Xusanman/praktikum_datasets

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 45 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (45/45), 7.17 MiB | 6.74 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [3]:
df = pd.read_csv("praktikum_datasets/uzbekistan.csv")
df.head(5)

          Boʻlinishi  Maydoni (kv.km)    Aholisi
0   Andijon viloyati           4200.0  1899000.0
1    Buxoro viloyati          39400.0  1384700.0
2  Fargʻona viloyati           6800.0  2597000.0
3    Jizzax viloyati          20500.0   910500.0
4    Xorazm viloyati           6300.0  1200000.0

In [4]:
pd.read_excel('praktikum_datasets/uzbekistan.xlsx', index_col=0, names=['hudud', 'maydon', 'aholi'])

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000

In [14]:
pd.read_csv("praktikum_datasets/automobile_data.csv", sep=",", index_col='index', nrows=15)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450
5,audi,sedan,99.8,177.3,ohc,five,110,19,15250
6,audi,wagon,105.8,192.7,ohc,five,110,19,18920
9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430
10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925
11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970
13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760
14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315
15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880
16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151
17,chevrolet,hatchback,94.5,155.9,ohc,four,70,38,6295